<a href="https://colab.research.google.com/github/hmyrcmn/AtfStudiosProject/blob/main/MultipleLineerRegresyon_PValueElimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
veriler = [
    ['tr', 130, 30, 10, 'e'],
    ['tr', 125, 36, 11, 'e'],
    ['tr', 135, 34, 10, 'k'],
    ['tr', 133, 30, 9, 'k'],
    ['tr', 129, 38, 12, 'e'],
    ['tr', 180, 90, 30, 'e'],
    ['tr', 190, 80, 25, 'e'],
    ['tr', 175, 90, 35, 'e'],
    ['tr', 177, 60, 22, 'k'],
    ['us', 185, 105, 33, 'e'],
    ['us', 165, 55, 27, 'k'],
    ['us', 155, 50, 44, 'k'],
    ['us', 160, 58, None, 'k'],
    ['us', 162, 59, 41, 'k'],
    ['us', 167, 62, 55, 'k'],
    ['fr', 174, 70, 47, 'e'],
    ['fr', 193, 90, None, 'e'],
    ['fr', 187, 80, 27, 'e'],
    ['fr', 183, 88, 28, 'e'],
    ['fr', 159, 40, 29, 'k'],
    ['fr', 164, 66, 32, 'k'],
    ['fr', 166, 56, 42, 'k']
]

# Verileri bir veri çerçevesine yükleyin
veri_cercevesi = pd.DataFrame(veriler, columns=['Ülke', 'Boy', 'Kilo', 'Yaş', 'Cinsiyet'])

# Veri çerçevesini gösterin
print(veri_cercevesi)
veri_cercevesi.to_csv('veriler.csv', index=False)



   Ülke  Boy  Kilo   Yaş Cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [32]:
data=pd.read_csv('veriler.csv')
data

Ülke  Boy  Kilo   Yaş Cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [33]:
#kukla değişken DUMMY VARIABLE
# bir değişkeni ifade edend başka bir değişken
# örnek cinsiyet semasında k verisinin k colonunda 1 - e kolonunda 0 olarak gösterilmesi



In [34]:
data=pd.read_csv('veriler.csv')
data

Ülke  Boy  Kilo   Yaş Cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [35]:
#veride null degerler varmı nasıl kodntrol edili
cauntNull=data.isnull().sum()
print(cauntNull)


Ülke        0
Boy         0
Kilo        0
Yaş         2
Cinsiyet    0
dtype: int64


In [36]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
Yas=data.iloc[:,1:4].values
print(Yas)

imputer =imputer.fit(Yas[:,1:4])
Yas[:,1:4]=imputer.transform(Yas[:,1:4])
print(Yas)

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]
[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


In [37]:
#YASDAKİ NULL DEGERLERİ DÜZENMENMİŞ VEİRLER
lastData2=pd.DataFrame(data=Yas,index=range(22),columns=["boy","kilo","yas"])
lastData2


boy   kilo    yas
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.00

In [38]:
country=data.iloc[:,0:1].values

print(country)

# caunty tr =1, us =2 fr=0 olrak düzenlendi
from sklearn import preprocessing
# LABEL ENCODER  SSAYISAL DEĞER VEİRRİ 0 1-2-3
le=preprocessing.LabelEncoder()
country[:,0]=le.fit_transform(data.iloc[:,0])
print(country)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ohe = OneHotEncoder() #use import with special library

# remember OneHotEncoder uding without ()
# ONE HOT ENCODER COLON BAŞLIKLARI İLE ATAMA YAPARAK COLONA AİDİYETİN 0 -1 İLE İFADE EDİLMESİNİ SAĞLAR :
# TR COLONUND VERİ 1 DEGERİ TAŞIYORSA O KİŞİ TR  O İSE TR DEĞİL FR YA DA US
#ohe=preprocessing.OneHotEncoder

country = ohe.fit_transform(country).toarray()
print("One-Hot Encoded Ülke Dizisi:")
print(country)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
One-Hot Encoded Ülke Dizisi:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [39]:
#verirlerin birleştirilmesi
data
lastData=pd.DataFrame(data=country,index=range(22),columns=["fr","tr","us"])
lastData
# işlenmiş country verilier getirildi bunlar düzenlenmiş  dönüştürülmüş kategorik veriler


fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [40]:
#lastData=pd.DataFrame(data=country,index=range(22),columns=["country"])
#lastData
# niye böyle anlamadım

In [41]:
gender=data.iloc[:,4].values
gender

array(['e', 'e', 'k', 'k', 'e', 'e', 'e', 'e', 'k', 'e', 'k', 'k', 'k',
       'k', 'k', 'e', 'e', 'e', 'e', 'k', 'k', 'k'], dtype=object)

In [42]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Gender verisini çekin
gender = data.iloc[:, 4].values

# LabelEncoder kullanarak cinsiyet verisini sayısal hale getirin
le = LabelEncoder()
gender_encoded = le.fit_transform(gender)
print("LabelEncoded Cinsiyet Verisi:")
print(gender_encoded)

# OneHotEncoder kullanarak sayısal cinsiyet verisini one-hot encoding yapın
ohe = OneHotEncoder(sparse=False)  # sparse=False ile seyrek matrisi önler
gender_onehot = ohe.fit_transform(gender_encoded.reshape(-1, 1))
print("One-Hot Encoded Cinsiyet Verisi:")
print(gender_onehot)


LabelEncoded Cinsiyet Verisi:
[0 0 1 1 0 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1]
One-Hot Encoded Cinsiyet Verisi:
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [43]:
lastData3=pd.DataFrame(data=gender_onehot,index=range(22),columns=["gender_e","gender_k"])
# kukla yaklaşımı önlemek için gender-onehot un ilk
lastData3

gender_e  gender_k
0        1.0       0.0
1        1.0       0.0
2        0.0       1.0
3        0.0       1.0
4        1.0       0.0
5        1.0       0.0
6        1.0       0.0
7        1.0       0.0
8        0.0       1.0
9        1.0       0.0
10       0.0       1.0
11       0.0       1.0
12       0.0       1.0
13       0.0       1.0
14       0.0       1.0
15       1.0       0.0
16       1.0       0.0
17       1.0       0.0
18       1.0       0.0
19       0.0       1.0
20       0.0       1.0
21       0.0       1.0

In [44]:
lastData3=pd.DataFrame(data=gender_onehot[:,:1],index=range(22),columns=["gender_ e",])
# kukla yaklaşımı önlemek için gender-onehot un ilk
lastData3

gender_ e
0         1.0
1         1.0
2         0.0
3         0.0
4         1.0
5         1.0
6         1.0
7         1.0
8         0.0
9         1.0
10        0.0
11        0.0
12        0.0
13        0.0
14        0.0
15        1.0
16        1.0
17        1.0
18        1.0
19        0.0
20        0.0
21        0.0

In [45]:
s=pd.concat([lastData,lastData2],axis=1)
s


fr   tr   us    boy   kilo    yas
0   0.0  1.0  0.0  130.0   30.0  10.00
1   0.0  1.0  0.0  125.0   36.0  11.00
2   0.0  1.0  0.0  135.0   34.0  10.00
3   0.0  1.0  0.0  133.0   30.0   9.00
4   0.0  1.0  0.0  129.0   38.0  12.00
5   0.0  1.0  0.0  180.0   90.0  30.00
6   0.0  1.0  0.0  190.0   80.0  25.00
7   0.0  1.0  0.0  175.0   90.0  35.00
8   0.0  1.0  0.0  177.0   60.0  22.00
9   0.0  0.0  1.0  185.0  105.0  33.00
10  0.0  0.0  1.0  165.0   55.0  27.00
11  0.0  0.0  1.0  155.0   50.0  44.00
12  0.0  0.0  1.0  160.0   58.0  28.45
13  0.0  0.0  1.0  162.0   59.0  41.00
14  0.0  0.0  1.0  167.0   62.0  55.00
15  1.0  0.0  0.0  174.0   70.0  47.00
16  1.0  0.0  0.0  193.0   90.0  28.45
17  1.0  0.0  0.0  187.0   80.0  27.00
18  1.0  0.0  0.0  183.0   88.0  28.00
19  1.0  0.0  0.0  159.0   40.0  29.00
20  1.0  0.0  0.0  164.0   66.0  32.00
21  1.0  0.0  0.0  166.0   56.0  42.00

In [46]:
#verilerin birleştirilmesi
#axis=1 ile düzgün eşleşme sağlandı
data=pd.concat([lastData,lastData2,lastData3],axis=1)
data

# data artık işlenebilecek formata getirildi gender 1= erkek 0= kız  temsil ediyor kategorik veri artık sayısal veri formatında (using ohe)



fr   tr   us    boy   kilo    yas  gender_ e
0   0.0  1.0  0.0  130.0   30.0  10.00        1.0
1   0.0  1.0  0.0  125.0   36.0  11.00        1.0
2   0.0  1.0  0.0  135.0   34.0  10.00        0.0
3   0.0  1.0  0.0  133.0   30.0   9.00        0.0
4   0.0  1.0  0.0  129.0   38.0  12.00        1.0
5   0.0  1.0  0.0  180.0   90.0  30.00        1.0
6   0.0  1.0  0.0  190.0   80.0  25.00        1.0
7   0.0  1.0  0.0  175.0   90.0  35.00        1.0
8   0.0  1.0  0.0  177.0   60.0  22.00        0.0
9   0.0  0.0  1.0  185.0  105.0  33.00        1.0
10  0.0  0.0  1.0  165.0   55.0  27.00        0.0
11  0.0  0.0  1.0  155.0   50.0  44.00        0.0
12  0.0  0.0  1.0  160.0   58.0  28.45        0.0
13  0.0  0.0  1.0  162.0   59.0  41.00        0.0
14  0.0  0.0  1.0  167.0   62.0  55.00        0.0
15  1.0  0.0  0.0  174.0   70.0  47.00        1.0
16  1.0  0.0  0.0  193.0   90.0  28.45        1.0
17  1.0  0.0  0.0  187.0   80.0  27.00        1.0
18  1.0  0.0  0.0  183.0   88.0  28.00        1.0
19  1.0  0.0  0.0  159.0   40.0  29.00        0.0
20  1.0  0.0  0.0  164.0   66.0  32.00        0.0
21  1.0  0.0  0.0  166.0   56.0  42.00        0.0

In [47]:
boy=data.iloc[:,3:4].values
boy

array([[130.],
       [125.],
       [135.],
       [133.],
       [129.],
       [180.],
       [190.],
       [175.],
       [177.],
       [185.],
       [165.],
       [155.],
       [160.],
       [162.],
       [167.],
       [174.],
       [193.],
       [187.],
       [183.],
       [159.],
       [164.],
       [166.]])

In [48]:
sag=data.iloc[:,4:]
sag

kilo    yas  gender_ e
0    30.0  10.00        1.0
1    36.0  11.00        1.0
2    34.0  10.00        0.0
3    30.0   9.00        0.0
4    38.0  12.00        1.0
5    90.0  30.00        1.0
6    80.0  25.00        1.0
7    90.0  35.00        1.0
8    60.0  22.00        0.0
9   105.0  33.00        1.0
10   55.0  27.00        0.0
11   50.0  44.00        0.0
12   58.0  28.45        0.0
13   59.0  41.00        0.0
14   62.0  55.00        0.0
15   70.0  47.00        1.0
16   90.0  28.45        1.0
17   80.0  27.00        1.0
18   88.0  28.00        1.0
19   40.0  29.00        0.0
20   66.0  32.00        0.0
21   56.0  42.00        0.0

In [49]:
sol=data.iloc[:,:3]
sol


fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [50]:
# Convert the numpy arrays to DataFrames
sol_df = pd.DataFrame(sol)
sag_df = pd.DataFrame(sag)

# Concatenate the DataFrames
veri = pd.concat([sol_df, sag_df], axis=1)
veri


fr   tr   us   kilo    yas  gender_ e
0   0.0  1.0  0.0   30.0  10.00        1.0
1   0.0  1.0  0.0   36.0  11.00        1.0
2   0.0  1.0  0.0   34.0  10.00        0.0
3   0.0  1.0  0.0   30.0   9.00        0.0
4   0.0  1.0  0.0   38.0  12.00        1.0
5   0.0  1.0  0.0   90.0  30.00        1.0
6   0.0  1.0  0.0   80.0  25.00        1.0
7   0.0  1.0  0.0   90.0  35.00        1.0
8   0.0  1.0  0.0   60.0  22.00        0.0
9   0.0  0.0  1.0  105.0  33.00        1.0
10  0.0  0.0  1.0   55.0  27.00        0.0
11  0.0  0.0  1.0   50.0  44.00        0.0
12  0.0  0.0  1.0   58.0  28.45        0.0
13  0.0  0.0  1.0   59.0  41.00        0.0
14  0.0  0.0  1.0   62.0  55.00        0.0
15  1.0  0.0  0.0   70.0  47.00        1.0
16  1.0  0.0  0.0   90.0  28.45        1.0
17  1.0  0.0  0.0   80.0  27.00        1.0
18  1.0  0.0  0.0   88.0  28.00        1.0
19  1.0  0.0  0.0   40.0  29.00        0.0
20  1.0  0.0  0.0   66.0  32.00        0.0
21  1.0  0.0  0.0   56.0  42.00        0.0

In [51]:
#eğitim ve test verilerinin oluştrulması
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(veri,boy,test_size=0.33,random_state=0)

x_train


fr   tr   us   kilo    yas  gender_ e
8   0.0  1.0  0.0   60.0  22.00        0.0
6   0.0  1.0  0.0   80.0  25.00        1.0
16  1.0  0.0  0.0   90.0  28.45        1.0
4   0.0  1.0  0.0   38.0  12.00        1.0
2   0.0  1.0  0.0   34.0  10.00        0.0
5   0.0  1.0  0.0   90.0  30.00        1.0
17  1.0  0.0  0.0   80.0  27.00        1.0
9   0.0  0.0  1.0  105.0  33.00        1.0
7   0.0  1.0  0.0   90.0  35.00        1.0
18  1.0  0.0  0.0   88.0  28.00        1.0
3   0.0  1.0  0.0   30.0   9.00        0.0
0   0.0  1.0  0.0   30.0  10.00        1.0
15  1.0  0.0  0.0   70.0  47.00        1.0
12  0.0  0.0  1.0   58.0  28.45        0.0

In [52]:
x_test

fr   tr   us  kilo   yas  gender_ e
20  1.0  0.0  0.0  66.0  32.0        0.0
10  0.0  0.0  1.0  55.0  27.0        0.0
14  0.0  0.0  1.0  62.0  55.0        0.0
13  0.0  0.0  1.0  59.0  41.0        0.0
1   0.0  1.0  0.0  36.0  11.0        1.0
21  1.0  0.0  0.0  56.0  42.0        0.0
11  0.0  0.0  1.0  50.0  44.0        0.0
19  1.0  0.0  0.0  40.0  29.0        0.0

In [53]:
y_train
y_train_df = pd.DataFrame(y_train)
y_train_df

0
0   177.0
1   190.0
2   193.0
3   129.0
4   135.0
5   180.0
6   187.0
7   185.0
8   175.0
9   183.0
10  133.0
11  130.0
12  174.0
13  160.0

In [54]:
y_test_df=pd.DataFrame(y_test)
y_test_df

0
0  164.0
1  165.0
2  167.0
3  162.0
4  125.0
5  166.0
6  155.0
7  159.0

In [55]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
# modeli inşa ediyor
lr.fit(x_train,y_train)


LinearRegression()

In [65]:
y_pred=lr.predict(x_test)
y_pred
y_pred_df=pd.DataFrame(y_pred)
y_pred_df

0
0  182.254965
1  153.601759
2  163.032433
3  158.791705
4  130.887516
5  173.757833
6  150.547256
7  157.276772

In [69]:
tahmin = pd.concat([y_test_df, y_pred_df], axis=1)
tahmin

0           0
0  164.0  182.254965
1  165.0  153.601759
2  167.0  163.032433
3  162.0  158.791705
4  125.0  130.887516
5  166.0  173.757833
6  155.0  150.547256
7  159.0  157.276772

In [76]:

import statsmodels.api as sm
# değişkenlerden hangisinin etkisi fazla? array a eklenir

X= np.append(arr=np.ones((22,1)).astype(int),values=veri, axis=1) # 22,1 lik çarpan oluşturuldu
X_l= veri.iloc[:,[0,1,2,3,4,5]].values # 6 kolonu al sonrasında elimine işlemi yapılacal p value degeri hesaplanacak
model=sm.OLS(boy,X_l).fit() # regresyon sonucu = isttaistiksel sonuçları çıkartmayı sağlıyor : boy bağımsız değişkenlerden ne kadar etkiledniyor
model.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.886
Model:                            OLS   Adj. R-squared:                  0.850
Method:                 Least Squares   F-statistic:                     24.85
Date:                Fri, 06 Oct 2023   Prob (F-statistic):           5.17e-07
Time:                        11:10:02   Log-Likelihood:                -73.887
No. Observations:                  22   AIC:                             159.8
Df Residuals:                      16   BIC:                             166.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           113.6364      8.087     14.052      0.000      96.493     130.780
x2           108.1800      5.644     19.167      0.000      96.215     120.145
x3           104.1324      8.840     11.780      0.000      85.393     122.871
x4             0.9142      0.120      7.624      0.000       0.660       1.168
x5             0.1054      0.221      0.478      0.639      -0.362       0.573
x6           -10.5082      5.005     -2.099      0.052     -21.119       0.102
==============================================================================
Omnibus:                        1.129   Durbin-Watson:                   2.772
Prob(Omnibus):                  0.569   Jarque-Bera (JB):                0.679
Skew:                           0.426   Prob(JB):                        0.712
Kurtosis:                       2.878   Cond. No.                         513.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [77]:
# x5 max p value elimine işlemi gerçekleştirilecek  yas en çok etkileyen değişken bu durumda
import statsmodels.api as sm
# değişkenlerden hangisinin etkisi fazla? array a eklenir

X= np.append(arr=np.ones((22,1)).astype(int),values=veri, axis=1) # 22,1 lik çarpan oluşturuldu
X_l= veri.iloc[:,[0,1,2,3,5]].values # 6 kolonu al sonrasında elimine işlemi yapılacal p value degeri hesaplanacak
model=sm.OLS(boy,X_l).fit() # regresyon sonucu = isttaistiksel sonuçları çıkartmayı sağlıyor : boy bağımsız değişkenlerden ne kadar etkiledniyor
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Fri, 06 Oct 2023   Prob (F-statistic):           9.32e-08
Time:                        11:12:34   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.000     101.451     129.866
x2           109.0786      5.200     20.978      0.000      98.108     120.049
x3           106.5445      7.090     15.026      0.000      91.585     121.504
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5           -11.1093      4.733     -2.347      0.031     -21.096      -1.123
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         397.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [78]:
# x5 elimine edilecek  cinsiyet yaştan sonra bağımsız değişkeni en çok etkileyen ikin bağımsız değişken
import statsmodels.api as sm
# değişkenlerden hangisinin etkisi fazla? array a eklenir

X= np.append(arr=np.ones((22,1)).astype(int),values=veri, axis=1) # 22,1 lik çarpan oluşturuldu
X_l= veri.iloc[:,[0,1,2,3]].values # 6 kolonu al sonrasında elimine işlemi yapılacal p value degeri hesaplanacak
model=sm.OLS(boy,X_l).fit() # regresyon sonucu = isttaistiksel sonuçları çıkartmayı sağlıyor : boy bağımsız değişkenlerden ne kadar etkiledniyor
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Fri, 06 Oct 2023   Prob (F-statistic):           1.52e-07
Time:                        11:12:56   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.000     104.550     135.077
x2           109.8084      5.804     18.919      0.000      97.615     122.002
x3           114.4212      6.984     16.382      0.000      99.747     129.095
x4             0.7904      0.092      8.595      0.000       0.597       0.984
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.855
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                1.499
Skew:                           0.605   Prob(JB):                        0.473
Kurtosis:                       3.416   Cond. No.                         369.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""